set nocompatible
behave mswin
set guifont=Consolas:h10:cANSI
set guioptions-=T
set helplang=En
colorscheme drunkcod
set softtabstop=2
syntax on
set number
set columns=101
set backspace=indent,eol,start
